rails g destroy Documento
rails g destroy Pessoa
rails g destroy Credencial
rails g destroy Aluno
rails g destroy Funcionario
rails g destroy Relatorio
rails g destroy RelatorioAssistenteSocial
rails g destroy RelatorioPsicologico
rails g destroy RelatorioGeral
